# Generated by Django 5.2 on 2025-04-06 02:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether this project uses an image or video', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for project video (only used if Media Type is set to Video)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this project', max_length=255, null=True, verbose_name='image'),
        ),
    ]
