# Generated by Django 5.2 on 2025-04-06 02:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_media_type_project_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video file directly (MP4, WebM, etc.)', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='project',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('video_url', 'Video URL')], default='image', help_text='Choose the type of media for this project', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for project video (only used if Media Type is set to Video URL)', null=True),
        ),
    ]
